### ISSUE TITLE
Index not rolling on min_size

### ISSUE THREAD

**Issue by jgprogramming** [opendistro-for-elasticsearch/index-management#117]
Hey,

We're experiencing an issue with our ILM configuration. Our current index has over 40GB of data

```
health status index                                           uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   test-000001 kc1l8oBFS8-LXnBrQNWIng   3   0   11415100            0      242gb          242gb
```

and our ILM policy is defined as

```
{
    "policy_id": "test",
    "description": "Policy for application: test",
    "last_updated_time": 1574861831914,
    "schema_version": 1,
    "error_notification": null,
    "default_state": "Hot",
    "states": [
        {
            "name": "Hot",
            "actions": [
                {
                    "rollover": {
                        "min_size": "40gb",
                        "min_index_age": "2d"
                    }
                }
            ],
            "transitions": [
                {
                    "state_name": "Warm",
                    "conditions": {
                        "min_index_age": "5d"
                    }
                }
            ]
        },
        {
            "name": "Warm",
            "actions": [
                {
                    "allocation": {
                        "require": {
                            "box_type": "warm"
                        },
                        "wait_for": false
                    }
                }
            ],
            "transitions": []
        }
    ]
}
```

It is able to rollover every two days but fails to rollover on increased size. Did we misconfigure something? This index is in `"Attempting to rollover"` state constantly.

**Comment by jinsoor-amzn** [comment]
The fix is pushed to master branch. Closing this issue.

**Comment by daskanu** [comment]
@jinsoor-amzn 
We are using Release 1.6 and min_size is still not working for us.

**Comment by philipp1992** [comment]
can confirm its still not working with 1.6

**Comment by dbbaughe** [comment]
Hey @daskanu and @philipp1992,

Could you provide some more information?
What specifically is not working? Is it stuck at attempting to rollover?

Could you provide:
* An example of your policy 
* The GET <index>/_stats API response for the index you applied it to
* The GET _opendistro/_ism/explain/<index> API response for the index you applied it to

**Comment by daskanu** [comment]
@dbbaughe 
Yes, it gets stuck at "Attempting to rollover" when using 'min_size.'
When I test with 'min_doc_count' it works like a charm.
Thanks for your help. :)
**Here is my policy (small min_size for testing):**
{
    "policy": {
        "description": "Ingest, Rollover and Delete",
        "default_state": "ingest",
        "states": [
            {
                "name": "ingest",
                "actions": [
                    {
                        "rollover": {
                            "min_size": "10mb"
                        }
                    }
                ],
                "transitions": [
                    {
                        "state_name": "search"
                    }
                ]
            },
            {
                "name": "search",
                "actions": [],
                "transitions": [
                    {
                        "state_name": "delete",
                        "conditions": {
                            "min_index_age": "1h"
                        }
                    }
                ]
            },
            {
                "name": "delete",
                "actions": [
                    {
                        "delete": {}
                    }
                ],
                "transitions": []
            }
        ]
    }
}

**_stats of my Index:**
{
  "_shards" : {
    "total" : 9,
    "successful" : 9,
    "failed" : 0
  },
  "_all" : {
    "primaries" : {
      "docs" : {
        "count" : 1323,
        "deleted" : 0
      },
      "store" : {
        "size_in_bytes" : 12614273
      },
      "indexing" : {
        "index_total" : 20949,
        "index_time_in_millis" : 7943,
        "index_current" : 0,
        "index_failed" : 0,
        "delete_total" : 0,
        "delete_time_in_millis" : 0,
        "delete_current" : 0,
        "noop_update_total" : 0,
        "is_throttled" : false,
        "throttle_time_in_millis" : 0
      },
      "get" : {
        "total" : 0,
        "time_in_millis" : 0,
        "exists_total" : 0,
        "exists_time_in_millis" : 0,
        "missing_total" : 0,
        "missing_time_in_millis" : 0,
        "current" : 0
      },
      "search" : {
        "open_contexts" : 0,
        "query_total" : 9,
        "query_time_in_millis" : 25,
        "query_current" : 0,
        "fetch_total" : 6,
        "fetch_time_in_millis" : 1208,
        "fetch_current" : 0,
        "scroll_total" : 0,
        "scroll_time_in_millis" : 0,
        "scroll_current" : 0,
        "suggest_total" : 0,
        "suggest_time_in_millis" : 0,
        "suggest_current" : 0
      },
      "merges" : {
        "current" : 0,
        "current_docs" : 0,
        "current_size_in_bytes" : 0,
        "total" : 17,
        "total_time_in_millis" : 1152,
        "total_docs" : 3310,
        "total_size_in_bytes" : 10073280,
        "total_stopped_time_in_millis" : 0,
        "total_throttled_time_in_millis" : 0,
        "total_auto_throttle_in_bytes" : 62914560
      },
      "refresh" : {
        "total" : 202,
        "total_time_in_millis" : 4740,
        "external_total" : 178,
        "external_total_time_in_millis" : 4437,
        "listeners" : 0
      },
      "flush" : {
        "total" : 0,
        "periodic" : 0,
        "total_time_in_millis" : 0
      },
      "warmer" : {
        "current" : 0,
        "total" : 175,
        "total_time_in_millis" : 3
      },
      "query_cache" : {
        "memory_size_in_bytes" : 0,
        "total_count" : 0,
        "hit_count" : 0,
        "miss_count" : 0,
        "cache_size" : 0,
        "cache_count" : 0,
        "evictions" : 0
      },
      "fielddata" : {
        "memory_size_in_bytes" : 0,
        "evictions" : 0
      },
      "completion" : {
        "size_in_bytes" : 0
      },
      "segments" : {
        "count" : 28,
        "memory_in_bytes" : 465324,
        "terms_memory_in_bytes" : 386076,
        "stored_fields_memory_in_bytes" : 9168,
        "term_vectors_memory_in_bytes" : 0,
        "norms_memory_in_bytes" : 50432,
        "points_memory_in_bytes" : 0,
        "doc_values_memory_in_bytes" : 19648,
        "index_writer_memory_in_bytes" : 33505296,
        "version_map_memory_in_bytes" : 0,
        "fixed_bit_set_memory_in_bytes" : 0,
        "max_unsafe_auto_id_timestamp" : 1587533303798,
        "file_sizes" : { }
      },
      "translog" : {
        "operations" : 20949,
        "size_in_bytes" : 42091746,
        "uncommitted_operations" : 20949,
        "uncommitted_size_in_bytes" : 42091746,
        "earliest_last_modified_age" : 0
      },
      "request_cache" : {
        "memory_size_in_bytes" : 0,
        "evictions" : 0,
        "hit_count" : 0,
        "miss_count" : 0
      },
      "recovery" : {
        "current_as_source" : 0,
        "current_as_target" : 0,
        "throttle_time_in_millis" : 0
      }
    },
    "total" : {
      "docs" : {
        "count" : 2009,
        "deleted" : 0
      },
      "store" : {
        "size_in_bytes" : 35927568
      },
      "indexing" : {
        "index_total" : 62824,
        "index_time_in_millis" : 24058,
        "index_current" : 0,
        "index_failed" : 0,
        "delete_total" : 0,
        "delete_time_in_millis" : 0,
        "delete_current" : 0,
        "noop_update_total" : 0,
        "is_throttled" : false,
        "throttle_time_in_millis" : 0
      },
      "get" : {
        "total" : 0,
        "time_in_millis" : 0,
        "exists_total" : 0,
        "exists_time_in_millis" : 0,
        "missing_total" : 0,
        "missing_time_in_millis" : 0,
        "current" : 0
      },
      "search" : {
        "open_contexts" : 0,
        "query_total" : 9,
        "query_time_in_millis" : 25,
        "query_current" : 0,
        "fetch_total" : 6,
        "fetch_time_in_millis" : 1208,
        "fetch_current" : 0,
        "scroll_total" : 0,
        "scroll_time_in_millis" : 0,
        "scroll_current" : 0,
        "suggest_total" : 0,
        "suggest_time_in_millis" : 0,
        "suggest_current" : 0
      },
      "merges" : {
        "current" : 0,
        "current_docs" : 0,
        "current_size_in_bytes" : 0,
        "total" : 24,
        "total_time_in_millis" : 1748,
        "total_docs" : 3856,
        "total_size_in_bytes" : 13737572,
        "total_stopped_time_in_millis" : 0,
        "total_throttled_time_in_millis" : 0,
        "total_auto_throttle_in_bytes" : 188743680
      },
      "refresh" : {
        "total" : 316,
        "total_time_in_millis" : 8308,
        "external_total" : 282,
        "external_total_time_in_millis" : 7557,
        "listeners" : 0
      },
      "flush" : {
        "total" : 4,
        "periodic" : 0,
        "total_time_in_millis" : 101
      },
      "warmer" : {
        "current" : 0,
        "total" : 273,
        "total_time_in_millis" : 3
      },
      "query_cache" : {
        "memory_size_in_bytes" : 0,
        "total_count" : 0,
        "hit_count" : 0,
        "miss_count" : 0,
        "cache_size" : 0,
        "cache_count" : 0,
        "evictions" : 0
      },
      "fielddata" : {
        "memory_size_in_bytes" : 0,
        "evictions" : 0
      },
      "completion" : {
        "size_in_bytes" : 0
      },
      "segments" : {
        "count" : 73,
        "memory_in_bytes" : 1203029,
        "terms_memory_in_bytes" : 1014561,
        "stored_fields_memory_in_bytes" : 23568,
        "term_vectors_memory_in_bytes" : 0,
        "norms_memory_in_bytes" : 132736,
        "points_memory_in_bytes" : 0,
        "doc_values_memory_in_bytes" : 32164,
        "index_writer_memory_in_bytes" : 104789628,
        "version_map_memory_in_bytes" : 0,
        "fixed_bit_set_memory_in_bytes" : 0,
        "max_unsafe_auto_id_timestamp" : 1587533305195,
        "file_sizes" : { }
      },
      "translog" : {
        "operations" : 62812,
        "size_in_bytes" : 125300087,
        "uncommitted_operations" : 62812,
        "uncommitted_size_in_bytes" : 125300087,
        "earliest_last_modified_age" : 0
      },
      "request_cache" : {
        "memory_size_in_bytes" : 0,
        "evictions" : 0,
        "hit_count" : 0,
        "miss_count" : 0
      },
      "recovery" : {
        "current_as_source" : 0,
        "current_as_target" : 0,
        "throttle_time_in_millis" : 0
      }
    }
  },
  "indices" : {
    "okd_cocdit-000001" : {
      "uuid" : "i12RGAzcRw2ufnx5w0x0sQ",
      "primaries" : {
        "docs" : {
          "count" : 1323,
          "deleted" : 0
        },
        "store" : {
          "size_in_bytes" : 12614273
        },
        "indexing" : {
          "index_total" : 20949,
          "index_time_in_millis" : 7943,
          "index_current" : 0,
          "index_failed" : 0,
          "delete_total" : 0,
          "delete_time_in_millis" : 0,
          "delete_current" : 0,
          "noop_update_total" : 0,
          "is_throttled" : false,
          "throttle_time_in_millis" : 0
        },
        "get" : {
          "total" : 0,
          "time_in_millis" : 0,
          "exists_total" : 0,
          "exists_time_in_millis" : 0,
          "missing_total" : 0,
          "missing_time_in_millis" : 0,
          "current" : 0
        },
        "search" : {
          "open_contexts" : 0,
          "query_total" : 9,
          "query_time_in_millis" : 25,
          "query_current" : 0,
          "fetch_total" : 6,
          "fetch_time_in_millis" : 1208,
          "fetch_current" : 0,
          "scroll_total" : 0,
          "scroll_time_in_millis" : 0,
          "scroll_current" : 0,
          "suggest_total" : 0,
          "suggest_time_in_millis" : 0,
          "suggest_current" : 0
        },
        "merges" : {
          "current" : 0,
          "current_docs" : 0,
          "current_size_in_bytes" : 0,
          "total" : 17,
          "total_time_in_millis" : 1152,
          "total_docs" : 3310,
          "total_size_in_bytes" : 10073280,
          "total_stopped_time_in_millis" : 0,
          "total_throttled_time_in_millis" : 0,
          "total_auto_throttle_in_bytes" : 62914560
        },
        "refresh" : {
          "total" : 202,
          "total_time_in_millis" : 4740,
          "external_total" : 178,
          "external_total_time_in_millis" : 4437,
          "listeners" : 0
        },
        "flush" : {
          "total" : 0,
          "periodic" : 0,
          "total_time_in_millis" : 0
        },
        "warmer" : {
          "current" : 0,
          "total" : 175,
          "total_time_in_millis" : 3
        },
        "query_cache" : {
          "memory_size_in_bytes" : 0,
          "total_count" : 0,
          "hit_count" : 0,
          "miss_count" : 0,
          "cache_size" : 0,
          "cache_count" : 0,
          "evictions" : 0
        },
        "fielddata" : {
          "memory_size_in_bytes" : 0,
          "evictions" : 0
        },
        "completion" : {
          "size_in_bytes" : 0
        },
        "segments" : {
          "count" : 28,
          "memory_in_bytes" : 465324,
          "terms_memory_in_bytes" : 386076,
          "stored_fields_memory_in_bytes" : 9168,
          "term_vectors_memory_in_bytes" : 0,
          "norms_memory_in_bytes" : 50432,
          "points_memory_in_bytes" : 0,
          "doc_values_memory_in_bytes" : 19648,
          "index_writer_memory_in_bytes" : 33505296,
          "version_map_memory_in_bytes" : 0,
          "fixed_bit_set_memory_in_bytes" : 0,
          "max_unsafe_auto_id_timestamp" : 1587533303798,
          "file_sizes" : { }
        },
        "translog" : {
          "operations" : 20949,
          "size_in_bytes" : 42091746,
          "uncommitted_operations" : 20949,
          "uncommitted_size_in_bytes" : 42091746,
          "earliest_last_modified_age" : 0
        },
        "request_cache" : {
          "memory_size_in_bytes" : 0,
          "evictions" : 0,
          "hit_count" : 0,
          "miss_count" : 0
        },
        "recovery" : {
          "current_as_source" : 0,
          "current_as_target" : 0,
          "throttle_time_in_millis" : 0
        }
      },
      "total" : {
        "docs" : {
          "count" : 2009,
          "deleted" : 0
        },
        "store" : {
          "size_in_bytes" : 35927568
        },
        "indexing" : {
          "index_total" : 62824,
          "index_time_in_millis" : 24058,
          "index_current" : 0,
          "index_failed" : 0,
          "delete_total" : 0,
          "delete_time_in_millis" : 0,
          "delete_current" : 0,
          "noop_update_total" : 0,
          "is_throttled" : false,
          "throttle_time_in_millis" : 0
        },
        "get" : {
          "total" : 0,
          "time_in_millis" : 0,
          "exists_total" : 0,
          "exists_time_in_millis" : 0,
          "missing_total" : 0,
          "missing_time_in_millis" : 0,
          "current" : 0
        },
        "search" : {
          "open_contexts" : 0,
          "query_total" : 9,
          "query_time_in_millis" : 25,
          "query_current" : 0,
          "fetch_total" : 6,
          "fetch_time_in_millis" : 1208,
          "fetch_current" : 0,
          "scroll_total" : 0,
          "scroll_time_in_millis" : 0,
          "scroll_current" : 0,
          "suggest_total" : 0,
          "suggest_time_in_millis" : 0,
          "suggest_current" : 0
        },
        "merges" : {
          "current" : 0,
          "current_docs" : 0,
          "current_size_in_bytes" : 0,
          "total" : 24,
          "total_time_in_millis" : 1748,
          "total_docs" : 3856,
          "total_size_in_bytes" : 13737572,
          "total_stopped_time_in_millis" : 0,
          "total_throttled_time_in_millis" : 0,
          "total_auto_throttle_in_bytes" : 188743680
        },
        "refresh" : {
          "total" : 316,
          "total_time_in_millis" : 8308,
          "external_total" : 282,
          "external_total_time_in_millis" : 7557,
          "listeners" : 0
        },
        "flush" : {
          "total" : 4,
          "periodic" : 0,
          "total_time_in_millis" : 101
        },
        "warmer" : {
          "current" : 0,
          "total" : 273,
          "total_time_in_millis" : 3
        },
        "query_cache" : {
          "memory_size_in_bytes" : 0,
          "total_count" : 0,
          "hit_count" : 0,
          "miss_count" : 0,
          "cache_size" : 0,
          "cache_count" : 0,
          "evictions" : 0
        },
        "fielddata" : {
          "memory_size_in_bytes" : 0,
          "evictions" : 0
        },
        "completion" : {
          "size_in_bytes" : 0
        },
        "segments" : {
          "count" : 73,
          "memory_in_bytes" : 1203029,
          "terms_memory_in_bytes" : 1014561,
          "stored_fields_memory_in_bytes" : 23568,
          "term_vectors_memory_in_bytes" : 0,
          "norms_memory_in_bytes" : 132736,
          "points_memory_in_bytes" : 0,
          "doc_values_memory_in_bytes" : 32164,
          "index_writer_memory_in_bytes" : 104789628,
          "version_map_memory_in_bytes" : 0,
          "fixed_bit_set_memory_in_bytes" : 0,
          "max_unsafe_auto_id_timestamp" : 1587533305195,
          "file_sizes" : { }
        },
        "translog" : {
          "operations" : 62812,
          "size_in_bytes" : 125300087,
          "uncommitted_operations" : 62812,
          "uncommitted_size_in_bytes" : 125300087,
          "earliest_last_modified_age" : 0
        },
        "request_cache" : {
          "memory_size_in_bytes" : 0,
          "evictions" : 0,
          "hit_count" : 0,
          "miss_count" : 0
        },
        "recovery" : {
          "current_as_source" : 0,
          "current_as_target" : 0,
          "throttle_time_in_millis" : 0
        }
      }
    }
  }
}

**_opendistro/_ism/explain of my Index:**
{
  "okd_cocdit-000001" : {
    "index.opendistro.index_state_management.policy_id" : "rollover_delete",
    "index" : "okd_cocdit-000001",
    "index_uuid" : "i12RGAzcRw2ufnx5w0x0sQ",
    "policy_id" : "rollover_delete",
    "policy_seq_no" : 69,
    "policy_primary_term" : 20,
    "rolled_over" : false,
    "state" : {
      "name" : "ingest",
      "start_time" : 1587533603677
    },
    "action" : {
      "name" : "rollover",
      "start_time" : 1587533903633,
      "index" : 0,
      "failed" : false,
      "consumed_retries" : 0,
      "last_retry_time" : 0
    },
    "retry_info" : {
      "failed" : false,
      "consumed_retries" : 0
    },
    "info" : {
      "message" : "Attempting to rollover"
    }
  }
}

**Comment by daskanu** [comment]
OK, I have an update on this issue... It seems that a rollover with min_size condition is working, but the size of the primary shard reached 200MB, factor 20 higher than the set min_size value?!

So my question is, how often are these conditions evaluated?
Do the settings '**opendistro.index_state_management.job_interval**' and 'opendistro.index_state_management.coordinator.sweep_period' have an impact on this?

Thanks in advance for your help.

**Comment by dbbaughe** [comment]
Hi @daskanu,

When you say it reached 200MB which API are you using to check the size?

From your API responses it looks like the index is over the required 10MB so I would assume it rolls over on the next execution (which could be 0-5 minutes depending on when your last execution was if you're using default ODFE settings, but it's longer if you're on AmazonES).
```
"store" : {
      "size_in_bytes" : 12614273
},
```

`opendistro.index_state_management.coordinator.sweep_period` will have nothing to do with this, but 
`opendistro.index_state_management.job_interval` can affect this. The job interval is how frequently the rollover checks would happen. It defaults to 5 minutes for ODFE. So if you ingested 200MB in the span of 5 minutes then that's expected.

**Comment by daskanu** [comment]
Hi @dbbaughe,

I used the Indices-Page within Index Management. Would it be more precise to use a specific API call? I guess I have to do more testing with measuring the elapsed time when the rollover happens.

For now I would asume to close this issue since rollover with min_size is working.

**Comment by dbbaughe** [comment]
Hey @daskanu,

As long as you're referring to the `Primaries size` and not the `Total size` on the Indices page I believe it should be fine. We have an open issue to also include the current information about rollover conditions and transition conditions inside the `info` on the Managed Indices table which should show you exactly what values are being reported and used in the check. Will try to get this in for 1.7 so it's more clear.

If it was just because of elapsed time let us know, otherwise we can spend some more time trying to root cause what this could be.

Will keep it open for now in case @philipp1992 responds with his case.

Thanks!

**Comment by daskanu** [comment]
Hey @dbbaughe 
Today I tested the behaviour with min_size of 50MB and in the first attempt it took 9 minutes to trigger the rollover after the 50MB have been passed (Indices page - Primaries size). In the second attempt it took 120 minutes for the rollover to trigger.

But then I noticed something. When I refresh the Inidices page every 10 seconds, I can see that both the total size and primary size of my Index are increasing, but the document count stays still (not updating) even though I'm ingesting different documents all the time with a Filebeat-Logstash pipeline.

Suddenly out of nowhere the total documents count updates to the current value and after that within the default value of 5 minutes the rollover happens, WTF?

I also use the audit logging of the Security plugin and I can see that the document count is increasing continously (there is no value update freeze at all).

What the hell is wrong with my Index, why doesn't it show the same behaviour?
Both my index and the auditlog index have identically settings (3 shards and 2 replicas).

**Comment by dbbaughe** [comment]
Hi @daskanu,

Could you post your `<index>/_settings` and your cluster layout (# nodes, dedicated masters, etc.)?
Also are you using default refresh interval or was it changed to something longer for ingestion? Will try to replicate.

**Comment by daskanu** [comment]
Hi @dbbaughe

This is my default index setting:
```json
{
  "rsc_di_c4t-000001" : {
    "settings" : {
      "index" : {
        "opendistro" : {
          "index_state_management" : {
            "policy_id" : "default",
            "rollover_alias" : "rsc_di_c4t"
          }
        },
        "number_of_shards" : "3",
        "provided_name" : "rsc_di_c4t-000001",
        "creation_date" : "1587640037304",
        "number_of_replicas" : "2",
        "uuid" : "AePbGrwwRleB8FpXrxqqKw",
        "version" : {
          "created" : "7060199"
        }
      }
    }
  }
}
```

I run OpenDistro on Kubernetes with three dedicated master pods and three data-ingest pods (each with 8 vCPUs and 32GB RAM). Haven't changed any settings regarding the refresh interval, so I guess I'm on the default setting?

Thank you so much for your patience and helping with this. I really appriciate it.

**Comment by dbbaughe** [comment]
Hey @daskanu,

I will add something like this below to show the exact values being used when doing rollover comparisons.

We have similar condition logic in transitions, but showing the same values will have to wait a bit longer as it's slightly more complicated.

One thing I did notice while testing this, was that I had this job running every 1 minute, waited a while, and I added a few documents to the index being managed to take a screenshot and the stats did not update for a long time. There seems to be some logic that doesn't update the index stats if not actively queried for a while. The index stats only updated *after* I queried the index (and automatically after like ~5 minutes) so just curious if that could possibly be something you're running in to if you're only ingesting. This would mean size and doc count could be delayed while age should be accurate. Will need to potentially look into seeing if the stats request has options to force a refresh of stats for the index.

![Screen Shot 2020-04-24 at 12 10 07 PM](https://user-images.githubusercontent.com/46505179/80248524-f07eae00-8624-11ea-8c09-91c1e5d986de.png)

**Comment by dbbaughe** [comment]
Hey @daskanu,

The PR for the above has been merged
https://github.com/opendistro-for-elasticsearch/index-management/pull/208

If you'd like to be able to use it now you could use the artifact from the CI run here:
https://github.com/opendistro-for-elasticsearch/index-management/actions/runs/87163693

Otherwise it will be in the ODFE next release once Elasticsearch 7.7 comes out and probably soonish we will release updated standalone ISM zips for some of the versions that were already released as we have added a lot of improvements.

**Comment by dbbaughe** [comment]
Will close this with as the PR above was merged. If you still run into an issue with 7.7+ and can post the relevant condition information that would be helpful.
