### ISSUE TITLE
[BUG] Problem with applying templates for more than 10 ISM policys

### ISSUE THREAD

**Issue by mousemaxx** [opendistro-for-elasticsearch/index-management#429]
**Describe the bug**
"index_patterns" for ISM template for eleventh or more are not applied
Probably is the issue, the internal search for ISM templates (policies) is not specifying the size so it’s defaulting to only getting 10 of them.

**Other plugins installed**
ODFE 1.13.1

**To Reproduce**
The same policies are consistently created:
“policy_1” … “policy_11” with patterns “test_1- *” … “test_11- *”
the text does not matter, for example:
`{

“policy”: {
“policy_id”: “policy_1”,
“description”: “delete index after 7 days”,
“default_state”: “norm”,
“states”: [
{“name”: “norm”,“actions”: ,“transitions”: [{“state_name”: “del”,“conditions”: {“min_index_age”: “7d”}}]},
{“name”: “del”,“actions”: [{“delete”: {}}],“transitions”: }
],
“ism_template”: {
“index_patterns”: [“test_1-*”],
“priority”: 50
}
}
}`

after creating each policy, an index is created
**PUT test_X-1**
For the first 10, the policy is assigned, for the 11, no. Moreover, if, after creating 11 policies, you change any of the previously created ones, they also cease to be assigned
**GET _opendistro/_ism/explain/test_***
{
“test_1-1”: {
“index.opendistro.index_state_management.policy_id”: “**policy_1**”,
“index”: “test_1-1”,
“index_uuid”: “X1n6d3_YSLymYWHJVqTBow”,
“policy_id”: “policy_1”
},
“test_2-1”: {
“index.opendistro.index_state_management.policy_id”: “**policy_2**”,
“index”: “test_2-1”,
“index_uuid”: “h9olWdoPTYygyqjdlYVx2Q”,
“policy_id”: “policy_2”
},
“test_3-1”: {
“index.opendistro.index_state_management.policy_id”: “**policy_3**”,
“index”: “test_3-1”,
“index_uuid”: “t_Ejz_kMSna69o1iC3-o0A”,
“policy_id”: “policy_3”
},
“test_4-1”: {
“index.opendistro.index_state_management.policy_id”: “**policy_4**”,
“index”: “test_4-1”,
“index_uuid”: “q2WmtiqjQLysYZ-2miSXdQ”,
“policy_id”: “policy_4”
},
“test_5-1”: {
“index.opendistro.index_state_management.policy_id”: “**policy_5**”,
“index”: “test_5-1”,
“index_uuid”: “VziB0jHET5OqeapZbuOBew”,
“policy_id”: “policy_5”
},
“test_6-1”: {
“index.opendistro.index_state_management.policy_id”: “**policy_6**”,
“index”: “test_6-1”,
“index_uuid”: “Wn_cwBCpR9KwtiIhK7kyuw”,
“policy_id”: “policy_6”
},
“test_7-1”: {
“index.opendistro.index_state_management.policy_id”: “**policy_7**”,
“index”: “test_7-1”,
“index_uuid”: “jgyoskK6Ts6Da0lBZcUz8Q”,
“policy_id”: “policy_7”
},
“test_8-1”: {
“index.opendistro.index_state_management.policy_id”: “**policy_8**”,
“index”: “test_8-1”,
“index_uuid”: “0jSSQiImRfejIJgNsFR88A”,
“policy_id”: “policy_8”
},
“test_9-1”: {
“index.opendistro.index_state_management.policy_id”: “**policy_9**”,
“index”: “test_9-1”,
“index_uuid”: “tceow8_ZQVCylAO-LNUrHA”,
“policy_id”: “policy_9”
},
“test_10-1”: {
“index.opendistro.index_state_management.policy_id”: “**policy_10**”,
“index”: “test_10-1”,
“index_uuid”: “Nkwvq42USK60HLi0BbbP4A”,
“policy_id”: “policy_10”
},
"test_11-1": {
**“index.opendistro.index_state_management.policy_id”: null**
}
}

Policy (policy_11) starts working **without any changes** if I delete a block “ism_template”: {“index_patterns […]}” in any of the 10 previously created ones.

**Additional context**
preliminary discussion [here](https://discuss.opendistrocommunity.dev/t/problem-with-automatically-adds-policy/5475/12)

**Comment by bowenlan-amzn** [comment]
Addressed in PR #432 , thanks for reporting this!

**Comment by ThePsyjo** [comment]
here is a script to fix policies until this change is released
https://gist.github.com/ThePsyjo/e046e1b452db14b15ee643b4a0c21224

**Comment by vaibhavtandale786** [comment]
I was currently using ODFE 1.13.2 version.. but still facing the same problem.

**Comment by arusahni** [comment]
@bowenlan-amzn thanks for getting this merged. Is there currently a plan to fix this in OpenDistro, or are we required to migrate to OpenSearch?

**Comment by bowenlan-amzn** [comment]
Sorry, we have been focused on OpenSearch side releases. But we will continue to issue maintenance release of ODFE maybe every quarter, starting with one in Dec.
